Ideal
msurmava/week1 pull request #1
Opened 2022-03-30 08:27 UTC by msurmava

2022-04-01 13:35 UTC, cyberik-dev commented on optimal/Ideal.rb
> +    def optimal
let's call it 'call' 

Service objects are single business actions. You can change the name of your public method if you like. I prefer using call

2022-04-01 13:58 UTC, msurmava commented on optimal/Ideal.rb
> +class Ideal_weight
done

2022-04-01 13:58 UTC, msurmava commented on optimal/Ideal.rb
> +    def validate_parameters
done

2022-04-01 13:58 UTC, msurmava commented on optimal/Ideal.rb
> +      if @height == 0
It returns message that user entered invalid height

2022-04-01 13:58 UTC, msurmava commented on optimal/Ideal.rb
> +    def optimal
done

2022-04-01 13:59 UTC, msurmava commented on optimal/Ideal.rb
> +    TOSUBTRACT = 100
I have constants inside of class

2022-04-02 11:34 UTC, cyberik-dev requested changes

2022-04-02 11:34 UTC, cyberik-dev commented on optimal/Ideal.rb
> +#calculates ideal weight by height
please do not capitalize the file name - Ideal.rb and this name should be corresponding with the class name

2022-04-02 11:34 UTC, cyberik-dev commented on optimal/Ideal.rb
> +      if @height == 0
change to `return unless @height <= 0`

2022-04-02 11:34 UTC, cyberik-dev commented on optimal/Ideal.rb
> +    TOSUBTRACT = 100
rename it to SUBTRACTOR

2022-04-02 11:34 UTC, cyberik-dev commented on optimal/Ideal.rb
> +    TOSUBTRACT = 100
the value should be 110

2022-04-02 11:34 UTC, cyberik-dev commented on optimal/Ideal.rb
> +      ideal = @height - TOSUBTRACT
and move to a method
```ruby
  def ideal_weight
    @ideal_weight ||= @height - SUBTRACTOR
  end
```

2022-04-02 11:34 UTC, cyberik-dev commented on optimal/Ideal.rb
> +      if ideal  < EDGE
move to 

```ruby
  def ideal_weight?
    ideal_weight < EDGE
  end
```

2022-04-04 06:35 UTC, msurmava commented on optimal/Ideal.rb
> +    private
done

2022-04-04 06:37 UTC, msurmava commented on optimal/Ideal.rb
> +      if @height == 0
done

2022-04-04 06:38 UTC, msurmava commented on optimal/Ideal.rb
> +    TOSUBTRACT = 100
corrected

2022-04-04 06:47 UTC, msurmava commented on optimal/Ideal.rb
> +      if ideal  < EDGE
done

2022-04-05 11:09 UTC, cyberik-dev requested changes

2022-04-05 11:09 UTC, cyberik-dev commented on idealweightcounter.rb
> +  def calculate_ideal_weight
please read about Ruby Memoization 
https://www.honeybadger.io/blog/ruby-rails-memoization/
https://www.justinweiss.com/articles/4-simple-memoization-patterns-in-ruby-and-one-gem/
https://thoughtbot.com/blog/ruby-memoization-and-alternatives

and use it here

2022-04-05 11:09 UTC, cyberik-dev commented on idealweightcounter.rb
> +  def calculate_ideal_weight
rename to ideal_weight and call this method instead of using variable @ideal

2022-04-05 11:17 UTC, cyberik-dev commented on idealweightcounter.rb
> +# calculates ideal weight by height
rubocop 

1 file inspected, 2 offenses detected, 2 offenses auto-correctable

2022-04-05 11:43 UTC, msurmava commented on idealweightcounter.rb
> +# calculates ideal weight by height
no more offenses

2022-04-08 12:19 UTC, merged