Area
msurmava/week1 pull request #2
Opened 2022-03-30 11:10 UTC by msurmava

2022-04-02 15:22 UTC, cyberik-dev requested changes

2022-04-02 15:22 UTC, cyberik-dev commented on area/triangle.rb
> +class Triangle
add `class AttributeError < StandardError; end`

2022-04-02 15:22 UTC, cyberik-dev commented on area/triangle.rb
> +    @base * @height * AREA
@base * @height / DIVIDER

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +    @base * @height * AREA
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +  AREA = 1/2.to_f
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +#calculates area of a triangle by base and height
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +  def validate_parameters
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +  def area
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +class Triangle
done

2022-04-04 06:22 UTC, msurmava commented on area/triangle.rb
> +    if @base <= 0 || @height  <=  0
done

2022-04-04 06:26 UTC, msurmava commented on area/triangle.rb
> +#calculates area of a triangle by base and height
done

2022-04-05 11:02 UTC, cyberik-dev commented on area/triangleareacalculator.rb
> +# calculates area of a triangle by base and height
good job, but fix rubocop remarks please

> 1 file inspected, 3 offenses detected, 3 offenses auto-correctable

2022-04-08 12:20 UTC, merged